title: Mohamed Kalanthar Hussain
logo: /assets/img/IMG-20210721-WA0005.jpg


description:


  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/mohamed-kalanthar-hussain-jahir-usain-19489a16a/">LinkedIn</a> |
  <a href="https://github.com/HussainPythonista">GitHub</a>
  
  <br>   
  <br>
  <br>
  I'm a student at Upgrad AI And ML program,I'm proud of to be part of the program
  <br>
  <br>
  <br>
  </p>



theme: jekyll-theme-minimal
